### ISSUE TITLE
Please read through the comments in this project

### ISSUE THREAD

**Issue by vgoklani** [VivekPa/AlphaAI#1]
Thanks for putting this code/blog together. Unfortunately your approach suffers from the same problems as other projects that use deep learning to *forecast* stock prices. You can review the comments here:

https://github.com/jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction

I did find your discussion of wavelets and autoencoders worthwhile, nice work!

**Comment by VivekPa** [comment]
thanks, will take note of it
