### ISSUE TITLE
requirements.txt file is missing

### ISSUE THREAD

**Issue by sriba** [VivekPa/AlphaAI#2]
In the Readme, it is mentioned that one needs to do pip install -r requirements.txt, but the file is missing in the repository.

**Comment by IronCraftMan** [comment]
This should install all the necessary dependencies: 
`pip install bokeh numpy Keras pandas_datareader pywt fix_yahoo_finance tensorflow matplotlib pandas aylien_news_api nltk rpy2 textblob vaderSentiment pywavelets`

**Comment by ENM1989** [comment]
:+1:
please add the requirements.txt

**Comment by VivekPa** [comment]
Requirements.txt added.
