### ISSUE TITLE
Yahoo data

### ISSUE THREAD

**Issue by HomunculusK** [VivekPa/AlphaAI#22]
I saw in your medium article you said you were using
`stock_data = pdr.get_data_yahoo(self.ticker, self.start, self.end)`
for data acquisition
yet in your sample data you had a time col which yahoo doesn't provide 
is there a way can I use this for daily prices? 
Thank you

**Comment by VivekPa** [comment]
The data currently used is tick data aggregated according to time/volume/dollars. You can definitely use the model for daily data but the results will differ.
