### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by labrax** [VivekPa/AlphaAI#4]
Hi, Thanks for the very nice work! I am reading through your code and I am having problems understanding some of the steps taken. I'd suggest adding more comments in your code. Nonetheless, your explanations in the README are very useful!

In preprocessing.py: What do you mean with features split? Also, the sequence of steps in `make_wavelet_train` is not clear: why you used part of the original signal (`macd = np.mean(x[5:] - np.mean(x)`)? And why you created the `indicators.csv` set?

You called your autoencoder a stacked autoencoder, while your approach does not construct the autoencoder model in a stacked manner: you do not train your layers in turns, but all 3 at once. Reference: http://ufldl.stanford.edu/wiki/index.php/Stacked_Autoencoders

**Comment by VivekPa** [comment]
ah okay, then my autoencoders are merely multilayered and not stacked
